[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
toml = "0.8.11"

gtk4 = "0.7.3"
gtk4-layer-shell = "0.2.0"

xdg = "2.5.2"

clap = {version = "4.5.1", features = ["env", "derive"]}
clap-serde-derive = "0.2.1"
tokio = {version="1.36.0", features=["full"]}
serde = {version="1.0.197", features=["derive"]}
